### PR TITLE
Support for bash executableShell on WSL

### PR DESCRIPTION
**Pull request by idanpa**
Tweak the argument passed to spawn for resolving #43.
Spawn does not support non-native shells, see https://github.com/nodejs/node/issues/19947.

### CODE REVIEW

**Comment by idanpa** [comment]
Tested on vscode 1.22.1 both on Ubuntu 17.10 and Windows 10 1803 (both with  cygwin64 and WSL)

**Comment by thisboyiscrazy** [comment]
Let me test this. It might also fix the problem I am having with cygwin. (Spawn add flags)

**Comment by thisboyiscrazy** [comment]
In 0.25.0 thanks

**Comment by idanpa** [comment]
Thank you for this great tool, helped me a lot, glad to help.

**Pull request merged**
